"""add_role_to_users

Revision ID: 41f7fa729e4a
Revises: dee4f46081f0
Create Date: 2026-07-14 16:27:39.570403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f7fa729e4a'
down_revision: Union[str, Sequence[str], None] = 'dee4f46081f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column allowing NULL temporarily
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    
    # 2. Backfill all existing corporate users to 'Engineer'
    op.execute("UPDATE users SET role = 'Engineer' WHERE role IS NULL")
    
    # 3. Alter the column constraint safely to NOT NULL
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
