"""add_document_status

Revision ID: d0d9fefdd988
Revises: 6d0af9352f5a
Create Date: 2026-07-02 14:48:00.495595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0d9fefdd988'
down_revision: Union[str, Sequence[str], None] = '6d0af9352f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema securely handling existing row states."""
    # 1. Add the status column as nullable=True first to accommodate older data rows safely
    op.add_column(
        'documents', 
        sa.Column(
            'status', 
            sa.Enum('UPLOADED', 'EXTRACTING', 'TEXT_EXTRACTED', 'CHUNKING', 'CHUNKED', 'EMBEDDING', 'INDEXING', 'READY', 'FAILED', name='documentstatus', native_enum=False), 
            nullable=True
        )
    )
    
    # 2. Backfill pre-existing document records to a valid baseline status state
    op.execute("UPDATE documents SET status = 'READY' WHERE status IS NULL")

    # 3. Lock down the structural NOT NULL rule safely
    op.alter_column('documents', 'status', nullable=False)
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
